### ISSUE TITLE
please remove private token from public access

### ISSUE THREAD

**Issue by InExtremo** [Oksird/TelegramBot#2]
https://github.com/Oksird/TelegramBot/blob/a6b97551b17373b949d134696d62639707cc32ad/goodsearchbot.java#L48

**Comment by NothingIsMatter** [comment]
You can use environment variables in your IDE instead.
https://stackoverflow.com/questions/13748784/setting-up-and-using-environment-variables-in-intellij-idea

**Comment by Oksird** [comment]
Thank
